apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo-c354"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo-c354"
  template:
    metadata:
      labels:
        app: "aksdemo-c354"
    spec:
      containers:
        - name: "aksdemo-c354"
          image: "acrdemo2808.azurecr.io/aksdemo"
          ports:
          - containerPort: 80