apiVersion: v1
kind: Service
metadata:
    name: "aksnocdemo-6bbe"
    labels:
        app: "aksnocdemo-6bbe"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksnocdemo-6bbe"