on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrqmdemo.azurecr.io
        username: ${{ secrets.acr_acrqmdemo_username }}
        password: ${{ secrets.acr_acrqmdemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrqmdemo.azurecr.io/aksdemoqm:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrqmdemo.azurecr.io/aksdemoqm:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemoqm_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-demo-qm8c0e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-demo-qm8c0e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-demo-qm8c0e
        container-registry-url: acrqmdemo.azurecr.io
        container-registry-username: ${{ secrets.acr_acrqmdemo_username }}
        container-registry-password: ${{ secrets.acr_acrqmdemo_password }}
        secret-name: aksdemoqmdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-demo-qm8c0e
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          acrqmdemo.azurecr.io/aksdemoqm:${{ github.sha }}
        imagepullsecrets: |
          aksdemoqmdockerauth
